{% set name = "snowexsql" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snowexsql-{{ version }}.tar.gz
  sha256: f94948aab57ed1488049f5d947c3d1f7bc4b998c7ec083d2c4d62278971e5e0b

build:
  entry_points:
    - clear_dataset=snowexsql.cli:clear_dataset
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - utm >=0.5.0,<1.0
    - geoalchemy2 >=0.6,<1.0
    - geopandas >=0.7,<2.0
    - psycopg2-binary >=2.9.0,<2.10.0
    - rasterio >=1.1.5
    - sqlalchemy >=2.0.0

test:
  imports:
    - snowexsql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SnowEx/snowexsql
  summary: SQL Database software for SnowEx data
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  description: |
    Database access and tools for using the SnowEx database.
    This tool is simply a client for accessing the database using python.
  doc_url: https://snowexsql.readthedocs.io

extra:
  recipe-maintainers:
    - micah-prime
